CREATE TABLE IF NOT EXISTS community (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    score INTEGER,
    district VARCHAR(255),
    ranking INTEGER NOT NULL DEFAULT 0,
    waste_reports INTEGER NOT NULL DEFAULT 0,
    clean_up_activities INTEGER NOT NULL DEFAULT 0,
    resolved_reports INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(50),
    community_id BIGINT REFERENCES community(id)
);

CREATE TABLE IF NOT EXISTS eco_trike (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trike_code VARCHAR(255),
    status VARCHAR(50),
    battery_level DOUBLE PRECISION,
    operator_id BIGINT REFERENCES app_users(id)
);

CREATE TABLE IF NOT EXISTS waste_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    status VARCHAR(50),
    location VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    image_url VARCHAR(255),
    created_at TIMESTAMP,
    public_submission BOOLEAN NOT NULL DEFAULT FALSE,
    public_reporter_name VARCHAR(255),
    public_phone_number VARCHAR(255),
    user_id BIGINT REFERENCES app_users(id),
    community_id BIGINT REFERENCES community(id)
);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    message VARCHAR(255),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    user_id BIGINT REFERENCES app_users(id)
);

CREATE TABLE IF NOT EXISTS waste_collection_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT REFERENCES waste_reports(id),
    ecotrike_id BIGINT REFERENCES eco_trike(id),
    status VARCHAR(50),
    assigned_at TIMESTAMP
);
